apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: x
    helm:
      values: |
        adminPassword: admin
        ingress:
          enabled: true
          hosts:
            - "grafana.127-0-0-1.nip.io"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
