apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  destination:
    namespace: tempo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: x
    helm:
      values: |
        env:
          GF_AUTH_ANONYMOUS_ENABLED: true
          GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
          GF_AUTH_DISABLE_LOGIN_FORM: true
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Tempo
                type: tempo
                access: proxy
                orgId: 1
                url: http://tempo:3100
                basicAuth: false
                isDefault: true
                version: 1
                editable: false
                apiVersion: 1
                uid: tempo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
