apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    namespace: promtail
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: x
    helm:
      values: |
        config:
          logLevel: info
          clients:
            - url: http://loki.loki:3100/loki/api/v1/push
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
